# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
    vmImage: 'Ubuntu-16.04'

variables:
#    imageName: 'homesite:$(build.buildId)'
    imageName: 'homesite:0.1'

#job: build source into docker image
#    displayName: 'build docker image'

    steps:
    - script: npm install --only=prod
        displayName: 'npm install in client'
        workingDirectory: client

    - script: npm install --only=prod
        displayName: 'npm install in server'
        workingDirectory: server
    
    - script: ng build 
        displayName: 'build Angular client'
        workingDirectory: client

    - script: docker build -f Dockerfile -t $(imageName) .
        displayName: 'docker build'
    
