# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

variables:
#    imageName: 'homesite:$(build.buildId)'
  imageName: 'homesite:0.1'
  azureSubscription: DockerHub
  azureSubscriptionEndpoint: DockerHub
  azureContainerRegistry: https://index.docker.io/v1/

jobs:
- job: firstJob
  displayName: docker build

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - script: |
      npm install
      npx -p @angular/cli ng build --prod
    displayName: 'Angular client build'
    workingDirectory: 'client'

  - script: npm install
    displayName: npm install in server
    workingDirectory: server

  - script: docker build -f Dockerfile -t $(dockerId)/$(imageName) .
    displayName: docker build
    
  # - task: Docker@1
  #   displayName: Container registry login
  #   inputs:
  #     command: login
  #     containerregistrytype: Container Registry
  #     dockerRegistryEndpoint: Contoso

  - task: Docker@1
    displayName: Container registry login
    inputs:
      command: login
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: DockerHub
 
  - task: Docker@1
    displayName: Push image
    inputs:
      command: push
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: DockerHub
      # azureContainerRegistry: $(azureContainerRegistry)
      imageName: $(dockerId)/$(imageName)