# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

variables:
#    imageName: 'homesite:$(build.buildId)'
  imageName: 'homesite:0.1'

jobs:
- job: firstJob
  displayName: docker build

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - script: |
      npm install
      sudo npm install -g @angular/cli@6.2.3
      ng build --prod
    displayName: 'Angular client build'
    workingDirectory: 'client'

  - script: npm install --only=prod
    displayName: npm install in server
    workingDirectory: server

  - script: docker build -f Dockerfile -t $(imageName) .
    displayName: docker build
    
